import Foundation

/// The "What's New" shown on the first launch after an update. The content is `App/Resources/WhatsNew.json`,
/// generated by `scripts/release.sh` from the current version's block of `docs/Changelog.md` (the Changelog is the only source).
struct WhatsNew: Codable, Identifiable, Equatable {
    struct Section: Codable, Identifiable, Equatable {
        /// Section names of Keep a Changelog (Added / Changed / Fixed / Security)
        var name: String
        var items: [String]
        var id: String { name }

        var title: String {
            switch name {
            case "Added": L("新增")
            case "Changed": L("調整")
            case "Fixed": L("修正")
            case "Security": L("安全性")
            default: name
            }
        }
    }

    var version: String
    var date: String?
    var sections: [Section]
    var id: String { version }
}

extension WhatsNew {
    /// The version for which "What's New" was last shown (`CFBundleShortVersionString`)
    static let lastSeenKey = "lastSeenVersion"

    static var currentVersion: String {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? ""
    }

    /// Content bundled into the app; nil when missing, unreadable or empty
    static func bundled(_ bundle: Bundle = .main) -> WhatsNew? {
        guard let url = bundle.url(forResource: "WhatsNew", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let notes = try? JSONDecoder().decode(WhatsNew.self, from: data),
              notes.sections.contains(where: { !$0.items.isEmpty })
        else { return nil }
        return notes
    }

    /// Whether to show: the current version is newer than the last seen. With no record, a fresh install shows nothing (nothing is "new"),
    /// otherwise this is an update from a version before this feature and it should show.
    static func shouldShow(current: String, lastSeen: String?, isFreshInstall: Bool) -> Bool {
        guard let lastSeen else { return !isFreshInstall }
        return current.compare(lastSeen, options: .numeric) == .orderedDescending
    }

    /// Called at launch: returns the content to show and records the current version. A downgrade leaves the record unchanged, so it shows again only after upgrading.
    static func pendingOnLaunch(isFreshInstall: Bool,
                                defaults: UserDefaults = .standard,
                                current: String = currentVersion,
                                notes: WhatsNew? = bundled()) -> WhatsNew? {
        guard !current.isEmpty else { return nil }
        let lastSeen = defaults.string(forKey: lastSeenKey)
        let show = shouldShow(current: current, lastSeen: lastSeen, isFreshInstall: isFreshInstall)
        if lastSeen == nil || current.compare(lastSeen ?? "", options: .numeric) == .orderedDescending {
            defaults.set(current, forKey: lastSeenKey)
        }
        guard show, let notes, notes.version == current else { return nil }
        return notes
    }
}
