#!/usr/bin/env python3
"""Reads and writes docs/Changelog.md (Keep a Changelog format). Content is generated by git-cliff; see cliff.toml.

  changelog.py has-unreleased            exit 0 if there is a hand-written `## [Unreleased]` block, else 1
  changelog.py promote X.Y.Z             rename `## [Unreleased]` to `## [X.Y.Z] - today`
  changelog.py insert                    read a version block from stdin and insert it above the latest version
  changelog.py show X.Y.Z [--format md|json]
                                         print that version's content (without the heading line).
                                         md: release notes for GitHub Release and Sparkle;
                                         json: the app's "What's New" window (App/Resources/WhatsNew.json)

  --file PATH   Changelog to use (default docs/Changelog.md)
"""
import argparse
import datetime
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEFAULT_FILE = ROOT / "docs" / "Changelog.md"
HEADING = re.compile(r"^## \[(?P<name>[^\]]+)\](?: - (?P<date>.+))?$")


def sections(text):
    """[(name, date, content lines)] in file order. The name is `Unreleased` or a version."""
    out = []
    for line in text.split("\n"):
        m = HEADING.match(line)
        if m:
            out.append((m["name"], m["date"], []))
        elif out:
            out[-1][2].append(line)
    return out


def find(text, name):
    for section_name, date, lines in sections(text):
        if section_name == name:
            return date, "\n".join(lines).strip("\n")
    return None


def has_unreleased(text):
    found = find(text, "Unreleased")
    return found is not None and any(line.startswith("- ") for line in found[1].split("\n"))


def promote(text, version, today):
    if find(text, "Unreleased") is None:
        raise SystemExit("Changelog has no `## [Unreleased]` block")
    return text.replace("## [Unreleased]", f"## [{version}] - {today}", 1)


def insert(text, block):
    """Put the generated version block before the first `## [` (the title and intro come before it)."""
    block = block.strip("\n") + "\n\n"
    m = re.search(r"^## \[", text, re.M)
    if not m:
        return text.rstrip("\n") + "\n\n" + block.rstrip("\n") + "\n"
    return text[:m.start()] + block + text[m.start():]


def parse_body(body):
    """Turn the content into [{name, items}]; an item can continue on an indented next line."""
    result = []
    for line in body.split("\n"):
        if line.startswith("### "):
            result.append({"name": line[4:].strip(), "items": []})
        elif line.startswith("- ") and result:
            result[-1]["items"].append(line[2:].strip())
        elif line.startswith("  ") and line.strip() and result and result[-1]["items"]:
            result[-1]["items"][-1] += " " + line.strip()
    return [s for s in result if s["items"]]


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["has-unreleased", "promote", "insert", "show"])
    parser.add_argument("version", nargs="?")
    parser.add_argument("--file", type=pathlib.Path, default=DEFAULT_FILE)
    parser.add_argument("--format", choices=["md", "json"], default="md")
    args = parser.parse_args(argv)

    text = args.file.read_text(encoding="utf-8")

    if args.command == "has-unreleased":
        return 0 if has_unreleased(text) else 1

    if args.command == "promote":
        if not args.version:
            parser.error("promote needs a version")
        today = datetime.date.today().isoformat()
        args.file.write_text(promote(text, args.version, today), encoding="utf-8")
        return 0

    if args.command == "insert":
        args.file.write_text(insert(text, sys.stdin.read()), encoding="utf-8")
        return 0

    if not args.version:
        parser.error("show needs a version")
    found = find(text, args.version)
    if found is None:
        print(f"Changelog has no version {args.version}", file=sys.stderr)
        return 1
    date, body = found
    if args.format == "md":
        print(body)
    else:
        print(json.dumps({"version": args.version, "date": date, "sections": parse_body(body)},
                         ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
